import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { BadgeDollarSign, Bike, CircleDollarSign, ClipboardList, Landmark, Plus, Settings2, ShieldAlert, UsersRound, WalletCards } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

const adminMenu = [{ icon: ClipboardList, label: "نظرة عامة", path: "/admin" }, { icon: Bike, label: "إدارة المندوبين", path: "/admin/drivers" }, { icon: Settings2, label: "التسعير والعمولات", path: "/admin/drivers#pricing" }];
const serviceLabels: Record<string, string> = { person: "توصيل أفراد", parcel: "طلبات وطرود", documents: "مستندات", items: "مشتريات ومنتجات", other: "طلبات أخرى" };
const withdrawalLabels: Record<string, string> = { pending: "قيد المراجعة", approved: "معتمد", rejected: "مرفوض", paid: "تم الصرف" };

export default function AdminDrivers() {
  const { user, loading } = useAuth(); const enabled = user?.role === "admin";
  const utils = trpc.useUtils(); const drivers = trpc.admin.drivers.useQuery(undefined, { enabled }); const users = trpc.admin.users.useQuery(undefined, { enabled }); const rules = trpc.admin.pricingRules.useQuery(undefined, { enabled }); const withdrawals = trpc.admin.withdrawalRequests.useQuery(undefined, { enabled });
  const [form, setForm] = useState({ userId: "", displayName: "", phone: "", vehicleType: "موتوسيكل", vehiclePlate: "", commissionPercent: "10" });
  const [commissionInputs, setCommissionInputs] = useState<Record<number, string>>({});
  useEffect(() => { setCommissionInputs(Object.fromEntries((drivers.data || []).map((driver) => [driver.id, String(driver.commissionPercent)]))); }, [drivers.data]);
  const refresh = () => Promise.all([utils.admin.drivers.invalidate(), utils.admin.users.invalidate(), utils.admin.withdrawalRequests.invalidate()]);
  const createDriver = trpc.admin.createDriver.useMutation({ onSuccess: () => { toast.success("تم إنشاء ملف المندوب."); setForm({ userId: "", displayName: "", phone: "", vehicleType: "موتوسيكل", vehiclePlate: "", commissionPercent: "10" }); refresh(); }, onError: (error) => toast.error(error.message) });
  const updateStatus = trpc.admin.updateDriverStatus.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة المندوب."); utils.admin.drivers.invalidate(); }, onError: (error) => toast.error(error.message) });
  const updateCommission = trpc.admin.updateDriverCommission.useMutation({ onSuccess: () => { toast.success("تم حفظ العمولة للرحلات القادمة."); utils.admin.drivers.invalidate(); }, onError: (error) => toast.error(error.message) });
  const updatePricing = trpc.admin.updatePricingRule.useMutation({ onSuccess: () => { toast.success("تم حفظ قاعدة التسعير."); utils.admin.pricingRules.invalidate(); }, onError: (error) => toast.error(error.message) });
  const reviewWithdrawal = trpc.admin.reviewWithdrawal.useMutation({ onSuccess: () => { toast.success("تم تحديث طلب السحب."); utils.admin.withdrawalRequests.invalidate(); }, onError: (error) => toast.error(error.message) });
  const candidates = users.data?.filter((candidate) => candidate.role === "user") || [];
  function submitDriver(event: FormEvent<HTMLFormElement>) { event.preventDefault(); createDriver.mutate({ userId: Number(form.userId), displayName: form.displayName.trim(), phone: form.phone.trim(), vehicleType: form.vehicleType.trim(), vehiclePlate: form.vehiclePlate.trim() || undefined, commissionPercent: Number(form.commissionPercent) }); }
  function submitPricing(event: FormEvent<HTMLFormElement>, serviceType: "person" | "parcel" | "documents" | "items" | "other") { event.preventDefault(); const values = new FormData(event.currentTarget); updatePricing.mutate({ serviceType, baseFare: Number(values.get("baseFare")), perKmFare: Number(values.get("perKmFare")), minimumFare: Number(values.get("minimumFare")) }); }

  return <div dir="rtl">{loading ? <div className="min-h-screen bg-slate-50" /> : !enabled ? <main className="container py-16 text-center"><ShieldAlert className="mx-auto h-10 w-10 text-rose-600" /><h1 className="mt-4 text-xl font-black">هذه الصفحة للإدارة فقط</h1></main> : <DashboardLayout menuItems={adminMenu} title="إدارة التشغيل المالي"><div className="mx-auto max-w-7xl"><header><p className="text-xs font-extrabold tracking-[.16em] text-teal-700">السائقون والتسعير</p><h1 className="mt-2 text-3xl font-black text-[#082538]">مركز إدارة السائقين</h1><p className="mt-2 max-w-3xl text-sm font-medium leading-6 text-slate-600">أضف السائقين العاملين، اضبط عمولة التشغيل لكل سائق للرحلات القادمة، ثم راجع طلبات سحب صافي الأرباح في مكان واحد.</p></header>
  <section className="mt-8 grid gap-6 xl:grid-cols-[.82fr_1.18fr]"><article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Plus className="h-5 w-5 text-teal-700" /><h2 className="font-black text-[#082538]">إضافة مندوب عامل</h2></div><p className="mt-2 text-xs font-medium leading-6 text-slate-500">اختر حسابًا مسجلاً ثم أنشئ له ملف تشغيل. يمكن تعديل العمولة والحالة لاحقًا.</p><form onSubmit={submitDriver} className="mt-5 space-y-3"><select required value={form.userId} onChange={(event) => { const selected = candidates.find((candidate) => candidate.id === Number(event.target.value)); setForm({ ...form, userId: event.target.value, displayName: selected?.name || "", phone: selected?.phone || "" }); }} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm font-bold"><option value="">اختر حسابًا مسجلاً</option>{candidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name || candidate.email || `مستخدم #${candidate.id}`}</option>)}</select><input required value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} placeholder="اسم المندوب" className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /><input required value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="رقم هاتف المندوب" className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /><div className="grid grid-cols-2 gap-3"><input required value={form.vehicleType} onChange={(event) => setForm({ ...form, vehicleType: event.target.value })} placeholder="نوع المركبة" className="rounded-xl border border-slate-200 px-3 py-3 text-sm" /><input value={form.vehiclePlate} onChange={(event) => setForm({ ...form, vehiclePlate: event.target.value })} placeholder="رقم اللوحة" className="rounded-xl border border-slate-200 px-3 py-3 text-sm" /></div><label className="block text-xs font-extrabold text-slate-700">عمولة تشغيل المنصة (%)<input required min="0" max="80" inputMode="numeric" value={form.commissionPercent} onChange={(event) => setForm({ ...form, commissionPercent: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" /></label><button disabled={createDriver.isPending || !candidates.length} className="w-full rounded-xl bg-[#082538] px-4 py-3 text-sm font-extrabold text-white disabled:opacity-50">{createDriver.isPending ? "جارٍ الإضافة…" : "إنشاء ملف المندوب"}</button></form></article>
  <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><UsersRound className="h-5 w-5 text-[#df6547]" /><h2 className="font-black text-[#082538]">متابعة السائقين</h2></div><div className="mt-5 space-y-3">{drivers.data?.length ? drivers.data.map((driver) => <div key={driver.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-[#082538]">{driver.displayName}</p><p className="mt-1 text-xs font-medium text-slate-500">{driver.phone} · {driver.vehicleType}{driver.vehiclePlate ? ` · ${driver.vehiclePlate}` : ""}</p><p className="mt-2 text-xs font-bold text-slate-600">{driver.totalTrips} رحلة · الرصيد التراكمي {driver.totalEarnings} ج.م</p></div><select value={driver.availability} disabled={updateStatus.isPending} onChange={(event) => updateStatus.mutate({ driverId: driver.id, availability: event.target.value as "offline" | "online" | "suspended" })} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-extrabold text-slate-700"><option value="offline">غير متصل</option><option value="online">متاح</option><option value="suspended">موقوف</option></select></div><div className="mt-3 flex flex-wrap items-end gap-2 border-t border-slate-200 pt-3"><label className="text-xs font-bold text-slate-600">عمولة المنصة %<input inputMode="numeric" min="0" max="80" value={commissionInputs[driver.id] ?? String(driver.commissionPercent)} onChange={(event) => setCommissionInputs({ ...commissionInputs, [driver.id]: event.target.value })} className="mt-1 w-24 rounded-lg border border-slate-200 bg-white px-2 py-2 text-sm" /></label><button disabled={updateCommission.isPending} onClick={() => updateCommission.mutate({ driverId: driver.id, commissionPercent: Number(commissionInputs[driver.id] ?? driver.commissionPercent) })} className="rounded-lg border border-teal-200 bg-white px-3 py-2 text-xs font-extrabold text-teal-800">حفظ العمولة</button><span className="text-[11px] font-bold text-slate-400">تُطبق على طلبات تُسلّم بعد الحفظ.</span></div></div>) : <p className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm font-bold text-slate-500">لا توجد ملفات سائقين بعد.</p>}</div></article></section>
  <section id="pricing" className="mt-8 rounded-[2rem] border border-teal-100 bg-gradient-to-br from-white to-teal-50/60 p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Settings2 className="h-5 w-5 text-teal-700" /><h2 className="font-black text-[#082538]">قواعد التسعير حسب الخدمة</h2></div><span className="rounded-full bg-white px-3 py-1.5 text-xs font-extrabold text-teal-800">لا يقل سعر الكيلومتر عن 5 ج.م</span></div><p className="mt-2 text-xs font-medium leading-6 text-slate-500">السعر المعروض للعميل مرجعي في الحجز، بينما يعيد الخادم احتسابه بهذه القواعد عند إنشاء الطلب لحماية السعر من التعديل داخل المتصفح.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rules.data && Object.entries(rules.data).map(([serviceType, rule]) => <form key={serviceType} onSubmit={(event) => submitPricing(event, serviceType as "person" | "parcel" | "documents" | "items" | "other")} className="rounded-2xl bg-white p-4 ring-1 ring-teal-100"><h3 className="font-black text-[#082538]">{serviceLabels[serviceType]}</h3><div className="mt-4 grid grid-cols-3 gap-2"><label className="text-[11px] font-bold text-slate-500">رسوم بدء<input name="baseFare" type="number" min="0" defaultValue={rule.baseFare} className="mt-1 w-full rounded-lg border border-slate-200 px-2 py-2 text-sm text-slate-800" /></label><label className="text-[11px] font-bold text-slate-500">للكيلومتر<input name="perKmFare" type="number" min="5" defaultValue={rule.perKmFare} className="mt-1 w-full rounded-lg border border-slate-200 px-2 py-2 text-sm text-slate-800" /></label><label className="text-[11px] font-bold text-slate-500">حد أدنى<input name="minimumFare" type="number" min="0" defaultValue={rule.minimumFare} className="mt-1 w-full rounded-lg border border-slate-200 px-2 py-2 text-sm text-slate-800" /></label></div><button disabled={updatePricing.isPending} className="mt-4 w-full rounded-lg bg-[#082538] px-3 py-2 text-xs font-extrabold text-white">حفظ القاعدة</button></form>)}</div></section>
  <section className="mt-8 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><WalletCards className="h-5 w-5 text-violet-700" /><h2 className="font-black text-[#082538]">طلبات سحب الأرباح</h2></div><span className="text-xs font-bold text-slate-500">لا يُسجّل طلب كمدفوع قبل اعتماده.</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-right text-sm"><thead className="border-b border-slate-100 text-xs text-slate-500"><tr><th className="pb-3">السائق</th><th className="pb-3">المبلغ</th><th className="pb-3">الملاحظة</th><th className="pb-3">الحالة</th><th className="pb-3">الإجراء</th></tr></thead><tbody>{withdrawals.data?.length ? withdrawals.data.map((withdrawal) => <tr key={withdrawal.id} className="border-b border-slate-50"><td className="py-4 font-black text-[#082538]">{withdrawal.driver?.displayName || `سائق #${withdrawal.driverId}`}</td><td className="py-4 font-black">{withdrawal.amount} ج.م</td><td className="py-4 text-xs text-slate-500">{withdrawal.note || "—"}</td><td className="py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-extrabold text-slate-700">{withdrawalLabels[withdrawal.status] || withdrawal.status}</span></td><td className="py-4">{withdrawal.status === "pending" ? <div className="flex gap-2"><button disabled={reviewWithdrawal.isPending} onClick={() => reviewWithdrawal.mutate({ withdrawalId: withdrawal.id, status: "approved" })} className="rounded-lg bg-teal-600 px-3 py-2 text-xs font-extrabold text-white">اعتماد</button><button disabled={reviewWithdrawal.isPending} onClick={() => reviewWithdrawal.mutate({ withdrawalId: withdrawal.id, status: "rejected" })} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-extrabold text-rose-700">رفض</button></div> : withdrawal.status === "approved" ? <button disabled={reviewWithdrawal.isPending} onClick={() => reviewWithdrawal.mutate({ withdrawalId: withdrawal.id, status: "paid" })} className="rounded-lg bg-[#082538] px-3 py-2 text-xs font-extrabold text-white">تسجيل الصرف</button> : <span className="text-xs font-bold text-slate-400">مغلق</span>}</td></tr>) : <tr><td colSpan={5} className="py-10 text-center text-sm font-bold text-slate-500">لا توجد طلبات سحب بعد.</td></tr>}</tbody></table></div></section>
  <section className="mt-8 grid gap-4 sm:grid-cols-3"><article className="rounded-2xl bg-slate-950 p-5 text-white"><CircleDollarSign className="h-5 w-5 text-teal-300" /><p className="mt-5 text-xs font-bold text-white/65">عمولة شفافة</p><p className="mt-1 text-sm font-black">تُسجل عند التسليم فقط</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><BadgeDollarSign className="h-5 w-5 text-[#df6547]" /><p className="mt-5 text-xs font-bold text-slate-500">سعر الطلبات</p><p className="mt-1 text-sm font-black text-[#082538]">أعلى افتراضيًا من الأفراد</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><Landmark className="h-5 w-5 text-violet-700" /><p className="mt-5 text-xs font-bold text-slate-500">السجل التاريخي</p><p className="mt-1 text-sm font-black text-[#082538]">لا يُعاد احتساب الطلبات المسلّمة</p></article></section></div></DashboardLayout>}</div>;
}
