import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, Bike, FileUp, IdCard, ShieldAlert, UserRound, XCircle } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

const docs = [{ type: "national_id", label: "بطاقة الرقم القومي" }, { type: "driver_license", label: "رخصة القيادة" }, { type: "vehicle_registration", label: "رخصة المركبة" }, { type: "selfie", label: "صورة شخصية واضحة" }] as const;
const menu = [{ icon: Bike, label: "الطلبات المتاحة", path: "/driver" }, { icon: BadgeCheck, label: "اعتماد الحساب", path: "/driver/verification" }];
const toBase64 = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] || ""); reader.onerror = reject; reader.readAsDataURL(file); });

export default function DriverVerification() {
  const { user, loading } = useAuth(); const utils = trpc.useUtils(); const verification = trpc.driver.verification.useQuery(undefined, { enabled: Boolean(user) }); const [pendingType, setPendingType] = useState<string | null>(null); const inputs = useRef<Record<string, HTMLInputElement | null>>({});
  const upload = trpc.driver.uploadVerificationDocument.useMutation({ onSuccess: () => { toast.success("تم رفع المستند وإرساله للمراجعة."); utils.driver.verification.invalidate(); setPendingType(null); }, onError: (error) => { toast.error(error.message); setPendingType(null); } });
  const choose = async (type: typeof docs[number]["type"], file?: File) => { if (!file) return; if (file.size > 4_000_000) { toast.error("حجم المستند يجب ألا يتجاوز 4 ميجابايت."); return; } if (!["image/jpeg", "image/png", "application/pdf"].includes(file.type)) { toast.error("ارفع JPG أو PNG أو PDF فقط."); return; } setPendingType(type); const dataBase64 = await toBase64(file); upload.mutate({ documentType: type, fileName: file.name.replace(/[^A-Za-z0-9._-]/g, "_"), mimeType: file.type as "image/jpeg" | "image/png" | "application/pdf", dataBase64 }); };
  const driver = verification.data?.driver; const status = driver?.verificationStatus || "not_submitted"; const statusText = status === "approved" ? "تم الاعتماد" : status === "pending" ? "قيد المراجعة" : status === "rejected" ? "يتطلب استكمالًا" : "لم تُرسل المستندات بعد";
  return <div dir="rtl">{loading ? <div className="min-h-screen bg-slate-50" /> : <DashboardLayout menuItems={menu} title="اعتماد الحساب"><div className="mx-auto max-w-4xl"><header><p className="text-xs font-extrabold tracking-[.16em] text-teal-700">ملف المندوب</p><h1 className="mt-2 text-3xl font-black text-[#082538]">اعتماد الحساب والمستندات</h1><p className="mt-2 text-sm font-medium text-slate-600">ارفع المستندات المطلوبة بوضوح. لا يظهر محتواها سوى للإدارة لأغراض المراجعة.</p></header><section className={`mt-8 rounded-[2rem] p-5 ${status === "approved" ? "bg-teal-50" : status === "rejected" ? "bg-rose-50" : "bg-amber-50"}`}><div className="flex items-center gap-3">{status === "approved" ? <BadgeCheck className="h-7 w-7 text-teal-700" /> : status === "rejected" ? <XCircle className="h-7 w-7 text-rose-700" /> : <ShieldAlert className="h-7 w-7 text-amber-700" />}<div><p className="font-black text-[#082538]">الحالة: {statusText}</p>{driver?.verificationNote && <p className="mt-1 text-sm font-medium text-slate-700">ملاحظة الإدارة: {driver.verificationNote}</p>}</div></div></section><section className="mt-8 grid gap-4 sm:grid-cols-2">{docs.map((document) => { const uploaded = verification.data?.documents.filter((item) => item.documentType === document.type)[0]; return <article key={document.type} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><span className="rounded-xl bg-slate-100 p-2 text-slate-700"><IdCard className="h-5 w-5" /></span>{uploaded ? <a href={uploaded.fileUrl} target="_blank" rel="noreferrer" className="rounded-lg bg-teal-50 px-2.5 py-1.5 text-xs font-extrabold text-teal-800">عرض الملف</a> : null}</div><h2 className="mt-5 font-black text-[#082538]">{document.label}</h2><p className="mt-2 text-xs font-medium leading-6 text-slate-500">JPG أو PNG أو PDF، حتى 4 ميجابايت. يمكنك الرفع مجددًا لاستبدال الملف بالمراجعة الأحدث.</p><input ref={(node) => { inputs.current[document.type] = node; }} className="hidden" type="file" accept="image/jpeg,image/png,application/pdf" onChange={(event) => { choose(document.type, event.target.files?.[0]); event.currentTarget.value = ""; }} /><button disabled={pendingType === document.type} onClick={() => inputs.current[document.type]?.click()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#082538] px-4 py-3 text-sm font-extrabold text-white disabled:opacity-60"><FileUp className="h-4 w-4" />{pendingType === document.type ? "جارٍ الرفع…" : uploaded ? "رفع نسخة جديدة" : "رفع المستند"}</button></article>; })}</section></div></DashboardLayout>}</div>;
}
