import { useAuth } from "@/_core/hooks/useAuth";
import AppHeader from "@/components/AppHeader";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BadgeDollarSign, Bike, CalendarDays, CircleAlert, Landmark, Route, Send, WalletCards } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link } from "wouter";

const withdrawalStatus: Record<string, string> = { pending: "قيد المراجعة", approved: "معتمد للصرف", rejected: "مرفوض", paid: "تم الصرف" };
const withdrawalTone: Record<string, string> = { pending: "bg-amber-50 text-amber-800", approved: "bg-sky-50 text-sky-800", rejected: "bg-rose-50 text-rose-800", paid: "bg-teal-50 text-teal-800" };

function periodNet(orders: { deliveredAt: Date | null; driverEarnings: number }[], from: Date) {
  return orders.filter((order) => order.deliveredAt && new Date(order.deliveredAt) >= from).reduce((total, order) => total + order.driverEarnings, 0);
}

export default function DriverEarnings() {
  const { user, loading } = useAuth();
  const financial = trpc.driver.earnings.useQuery(undefined, { enabled: Boolean(user), retry: false });
  const utils = trpc.useUtils();
  const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const [formError, setFormError] = useState(""); const [success, setSuccess] = useState("");
  const requestWithdrawal = trpc.driver.requestWithdrawal.useMutation({ onSuccess: () => { setAmount(""); setNote(""); setFormError(""); setSuccess("تم إرسال طلب السحب للمراجعة."); utils.driver.earnings.invalidate(); }, onError: (error) => { setSuccess(""); setFormError(error.message); } });
  const summary = financial.data;
  const now = new Date(); const dayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate()); const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);

  function submitWithdrawal(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSuccess(""); const value = Number(amount); if (!Number.isInteger(value) || value <= 0) { setFormError("أدخل مبلغًا صحيحًا أكبر من صفر."); return; } requestWithdrawal.mutate({ amount: value, note: note.trim() || undefined }); }

  return <div dir="rtl" className="min-h-screen bg-[#f8fbfc]"><AppHeader /><main className="container py-8 sm:py-12"><Link href="/driver" className="inline-flex items-center gap-2 text-sm font-extrabold text-slate-600 no-underline hover:text-teal-700"><ArrowRight className="h-4 w-4" /> العودة لواجهة المندوب</Link>{loading || financial.isLoading ? <div className="mt-8 h-64 animate-pulse rounded-[2rem] bg-slate-200" /> : financial.error || !summary ? <section className="mt-8 rounded-[2rem] border border-dashed border-slate-300 bg-white p-10 text-center"><Bike className="mx-auto h-10 w-10 text-teal-700" /><h1 className="mt-4 text-xl font-black text-[#082538]">هذه الصفحة مخصصة للسائقين</h1><p className="mt-2 text-sm font-medium text-slate-600">ستظهر لك بيانات أرباحك بعد ربط حسابك بملف مندوب.</p></section> : <><div className="mt-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold tracking-[.16em] text-teal-700">المركز المالي للمندوب</p><h1 className="mt-2 text-3xl font-black text-[#082538]">أرباحي ومستحقاتي</h1><p className="mt-2 text-sm font-medium text-slate-600">يُحتسب الصافي فقط للطلبات التي تم تسليمها، وفق عمولة المنصة الظاهرة في كل رحلة.</p></div><span className="rounded-2xl bg-teal-50 px-4 py-3 text-sm font-black text-teal-800">عمولتي الحالية {summary.driver.commissionPercent}%</span></div>
  <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-[2rem] bg-[#082538] p-5 text-white shadow-[0_18px_35px_rgba(8,37,56,.16)]"><WalletCards className="h-5 w-5 text-teal-300" /><p className="mt-6 text-xs font-bold text-white/65">رصيد قابل للسحب</p><p className="mt-2 text-3xl font-black">{summary.availableToWithdraw} ج.م</p></article><article className="rounded-[2rem] border border-slate-200 bg-white p-5"><BadgeDollarSign className="h-5 w-5 text-teal-700" /><p className="mt-6 text-xs font-bold text-slate-500">صافي أرباحي</p><p className="mt-2 text-3xl font-black text-[#082538]">{summary.netEarnings} ج.م</p></article><article className="rounded-[2rem] border border-slate-200 bg-white p-5"><Landmark className="h-5 w-5 text-[#df6547]" /><p className="mt-6 text-xs font-bold text-slate-500">عمولة المنصة</p><p className="mt-2 text-3xl font-black text-[#082538]">{summary.platformCommission} ج.م</p></article><article className="rounded-[2rem] border border-slate-200 bg-white p-5"><CalendarDays className="h-5 w-5 text-violet-700" /><p className="mt-6 text-xs font-bold text-slate-500">صافي هذا الشهر</p><p className="mt-2 text-3xl font-black text-[#082538]">{periodNet(summary.orders, monthStart)} ج.م</p></article></section>
  <div className="mt-8 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><section className="rounded-[2rem] border border-teal-100 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Send className="h-5 w-5 text-teal-700" /><h2 className="font-black text-[#082538]">طلب سحب أرباح</h2></div><p className="mt-2 text-xs font-medium leading-6 text-slate-500">الرصيد المتاح لا يتضمن الطلبات قيد المراجعة أو المعتمدة. يمكنك تقديم طلب واحد قيد المراجعة في الوقت نفسه.</p><form onSubmit={submitWithdrawal} className="mt-5 space-y-3"><label className="block text-xs font-extrabold text-slate-700">المبلغ بالجنيه<input inputMode="numeric" min="1" max={summary.availableToWithdraw} value={amount} onChange={(event) => setAmount(event.target.value)} placeholder={`حتى ${summary.availableToWithdraw} ج.م`} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-teal-500" /></label><label className="block text-xs font-extrabold text-slate-700">ملاحظة للإدارة (اختيارية)<textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={500} rows={3} className="mt-2 w-full resize-none rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-teal-500" placeholder="مثل طريقة الاستلام المناسبة" /></label>{formError && <p className="flex gap-2 rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-800"><CircleAlert className="h-4 w-4 shrink-0" />{formError}</p>}{success && <p className="rounded-xl bg-teal-50 p-3 text-xs font-bold text-teal-800">{success}</p>}<button disabled={requestWithdrawal.isPending || summary.availableToWithdraw <= 0} className="w-full rounded-xl bg-[#082538] px-4 py-3 text-sm font-extrabold text-white disabled:cursor-not-allowed disabled:opacity-50">{requestWithdrawal.isPending ? "جارٍ الإرسال…" : "إرسال طلب السحب"}</button></form></section>
  <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Route className="h-5 w-5 text-teal-700" /><h2 className="font-black text-[#082538]">آخر الرحلات المسلّمة</h2></div><div className="mt-5 space-y-3">{summary.orders.length ? summary.orders.slice(0, 8).map((order) => <div key={order.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><div><p className="font-black text-[#082538]">{order.reference}</p><p className="mt-1 text-xs font-medium text-slate-500">{order.pickupAddress} ← {order.destinationAddress}</p><p className="mt-1 text-[11px] font-bold text-slate-400">إجمالي {order.estimatedFee} ج.م · عمولة {order.platformCommissionAmount} ج.م</p></div><strong className="rounded-xl bg-teal-50 px-3 py-2 text-sm text-teal-800">صافي {order.driverEarnings} ج.م</strong></div>) : <div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm font-bold text-slate-500">لا توجد رحلات مكتملة لعرض الأرباح بعد.</div>}</div></section></div>
  <section className="mt-8 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="font-black text-[#082538]">سجل طلبات السحب</h2><span className="text-xs font-bold text-slate-500">معلّق/معتمد/مدفوع = محجوز من الرصيد</span></div><div className="mt-4 space-y-2">{summary.withdrawals.length ? summary.withdrawals.map((withdrawal) => <div key={withdrawal.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 px-4 py-3"><div><p className="font-black text-[#082538]">{withdrawal.amount} ج.م</p><p className="mt-1 text-xs text-slate-500">{new Date(withdrawal.createdAt).toLocaleDateString("ar-EG")} {withdrawal.note ? `· ${withdrawal.note}` : ""}</p></div><span className={`rounded-full px-3 py-1 text-xs font-extrabold ${withdrawalTone[withdrawal.status] || "bg-slate-100 text-slate-600"}`}>{withdrawalStatus[withdrawal.status] || withdrawal.status}</span></div>) : <p className="rounded-xl border border-dashed border-slate-200 p-5 text-center text-sm font-bold text-slate-500">لم تُرسل أي طلبات سحب بعد.</p>}</div></section><p className="mt-6 text-center text-xs font-bold text-slate-400">صافي اليوم: {periodNet(summary.orders, dayStart)} ج.م · إجمالي قيمة الرحلات: {summary.grossFee} ج.م</p></>}</main></div>;
}
