import { useAuth } from "@/_core/hooks/useAuth";
import AppHeader from "@/components/AppHeader";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Bike, ClipboardList, Clock3, Package, Plus, ShieldCheck, UserRound } from "lucide-react";
import { Link } from "wouter";

const statusStyle = { new: { label: "جديد", className: "bg-blue-50 text-blue-700 ring-blue-100" }, in_progress: { label: "قيد التنفيذ", className: "bg-amber-50 text-amber-700 ring-amber-100" }, delivered: { label: "تم التسليم", className: "bg-teal-50 text-teal-700 ring-teal-100" } } as const;

export default function MyOrders() {
  const { isAuthenticated, loading } = useAuth();
  const orders = trpc.orders.mine.useQuery(undefined, { enabled: isAuthenticated });
  const dateFormatter = new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium", timeStyle: "short" });
  return <div dir="rtl" className="min-h-screen w-full max-w-full overflow-x-hidden bg-[#f8fbfc] text-slate-950"><AppHeader />
    <main className="container w-full max-w-full min-w-0 py-10 sm:py-14"><div className="flex flex-wrap items-end justify-between gap-5"><div className="min-w-0"><p className="text-xs font-extrabold tracking-[.18em] text-teal-700">مركز المتابعة</p><h1 className="mt-3 text-3xl font-black tracking-tight text-[#082538] sm:text-4xl">طلباتي</h1><p className="mt-3 text-sm font-medium text-slate-600">تابع حالة الطلبات المسجلة في حسابك داخل الغردقة.</p></div><div className="flex max-w-full flex-wrap gap-3"><Link href="/book/person" className="inline-flex items-center gap-2 rounded-xl bg-[#082538] px-4 py-3 text-sm font-extrabold text-white no-underline"><Plus className="h-4 w-4" /> طلب أفراد</Link><Link href="/book/parcel" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-extrabold text-slate-800 no-underline"><Package className="h-4 w-4" /> طلب شحنة</Link></div></div>
      {!loading && !isAuthenticated && <section className="mt-9 rounded-[2rem] border border-slate-200 bg-white p-8 text-center shadow-sm"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><ClipboardList className="h-7 w-7" /></span><h2 className="mt-5 text-xl font-black text-[#082538]">سجّل الدخول لمتابعة طلباتك</h2><p className="mx-auto mt-3 max-w-md text-sm font-medium leading-7 text-slate-600">سيظهر هنا سجل الطلبات التي أنشأتها وحالة كل طلب.</p><button onClick={() => startLogin()} className="mt-6 rounded-xl bg-teal-600 px-5 py-3 text-sm font-extrabold text-white">تسجيل الدخول</button></section>}
      {isAuthenticated && orders.isLoading && <div className="mt-9 grid gap-4"><div className="h-28 animate-pulse rounded-2xl bg-slate-200" /><div className="h-28 animate-pulse rounded-2xl bg-slate-200" /></div>}
      {isAuthenticated && orders.isError && <section className="mt-9 rounded-2xl border border-red-100 bg-red-50 p-6 text-sm font-bold text-red-700">تعذر تحميل طلباتك حاليًا. حدّث الصفحة أو حاول مرة أخرى.</section>}
      {isAuthenticated && !orders.isLoading && !orders.isError && orders.data?.length === 0 && <section className="mt-9 rounded-[2rem] border border-dashed border-slate-300 bg-white p-10 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#e9faf7] text-teal-700"><Bike className="h-7 w-7" /></span><h2 className="mt-5 text-xl font-black text-[#082538]">لا توجد طلبات بعد</h2><p className="mt-2 text-sm font-medium text-slate-600">اختر خدمة التوصيل المناسبة وابدأ أول مشوار.</p></section>}
      {isAuthenticated && orders.data && orders.data.length > 0 && <section className="mt-9 space-y-4">{orders.data.map((order) => { const status = statusStyle[order.status]; const Icon = order.serviceType === "person" ? UserRound : Package; return <article key={order.id} className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm transition hover:shadow-md sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-4"><span className={`rounded-2xl p-3 text-white ${order.serviceType === "person" ? "bg-teal-600" : "bg-[#ff7954]"}`}><Icon className="h-5 w-5" /></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-[#082538]">{order.serviceType === "person" ? "توصيل أفراد" : "توصيل طلبات ومنتجات"}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-extrabold ring-1 ${status.className}`}>{status.label}</span></div><p className="mt-2 text-xs font-bold text-slate-500">{order.reference} · {dateFormatter.format(new Date(order.createdAt))}</p></div></div><div className="text-left"><p className="text-xs font-bold text-slate-500">تقدير مبدئي</p><p className="mt-1 text-xl font-black text-[#082538]">{order.estimatedFee} <span className="text-xs text-teal-700">ج.م</span></p></div></div><div className="mt-5 grid gap-4 border-t border-slate-100 pt-5 sm:grid-cols-[1fr_1fr_auto]"><div><p className="text-xs font-bold text-slate-400">من</p><p className="mt-1 text-sm font-bold text-slate-700">{order.pickupAddress}</p></div><div><p className="text-xs font-bold text-slate-400">إلى</p><p className="mt-1 text-sm font-bold text-slate-700">{order.destinationAddress}</p></div><div className="flex items-center gap-2 text-xs font-bold text-teal-700"><Clock3 className="h-4 w-4" /> {dateFormatter.format(new Date(order.requestedFor))}</div></div>{order.contactless === 1 && <div className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#effcf9] px-3 py-2 text-xs font-extrabold text-teal-800"><ShieldCheck className="h-4 w-4" /> التوصيل دون تلامس مفعّل</div>}</article>; })}</section>}
    </main>
  </div>;
}
