import AppHeader from "@/components/AppHeader";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Bell, CheckCheck, Clock3, PackageCheck } from "lucide-react";
import { Link } from "wouter";

export default function NotificationsCenter() {
  const { isAuthenticated, loading } = useAuth(); const utils = trpc.useUtils(); const notifications = trpc.support.notifications.useQuery(undefined, { enabled: isAuthenticated, refetchInterval: 10000 }); const markRead = trpc.support.markNotificationsRead.useMutation({ onSuccess: () => utils.support.notifications.invalidate() });
  if (loading) return <div className="min-h-screen bg-[#f8fbfc]" />;
  return <div dir="rtl" className="min-h-screen bg-[#f8fbfc]"><AppHeader /><main className="container py-9 sm:py-12"><div className="mx-auto max-w-3xl"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-extrabold tracking-[.16em] text-teal-700">مركز المتابعة</p><h1 className="mt-2 text-3xl font-black text-[#082538]">الإشعارات</h1><p className="mt-2 text-sm font-medium text-slate-600">تابع تحديثات الطلبات والدعم والمدفوعات في مكان واحد.</p></div>{isAuthenticated && <button disabled={markRead.isPending || !notifications.data?.some((item) => !item.isRead)} onClick={() => markRead.mutate({})} className="inline-flex items-center gap-2 rounded-xl border border-teal-200 bg-white px-4 py-3 text-sm font-extrabold text-teal-800 disabled:opacity-50"><CheckCheck className="h-4 w-4" />تعليم الكل كمقروء</button>}</header>{!isAuthenticated ? <section className="mt-8 rounded-[2rem] border border-slate-200 bg-white p-10 text-center shadow-sm"><Bell className="mx-auto h-10 w-10 text-teal-700" /><h2 className="mt-4 text-xl font-black text-[#082538]">سجّل الدخول لرؤية الإشعارات</h2><Link href="/" className="mt-5 inline-flex rounded-xl bg-[#082538] px-4 py-3 text-sm font-extrabold text-white no-underline">العودة للرئيسية</Link></section> : <section className="mt-8 space-y-3">{notifications.data?.length ? notifications.data.map((item) => <article key={item.id} className={`rounded-2xl border p-5 shadow-sm ${item.isRead ? "border-slate-200 bg-white" : "border-teal-200 bg-teal-50/60"}`}><div className="flex gap-3"><span className={`rounded-xl p-2 ${item.isRead ? "bg-slate-100 text-slate-600" : "bg-teal-100 text-teal-700"}`}><PackageCheck className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><h2 className="font-black text-[#082538]">{item.title}</h2>{!item.isRead && <button onClick={() => markRead.mutate({ notificationIds: [item.id] })} className="text-xs font-extrabold text-teal-800">تمت القراءة</button>}</div><p className="mt-2 text-sm font-medium leading-6 text-slate-600">{item.body}</p><p className="mt-3 flex items-center gap-1.5 text-[11px] font-bold text-slate-400"><Clock3 className="h-3.5 w-3.5" />{new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.createdAt))}</p></div></div></article>) : <div className="rounded-[2rem] border border-dashed border-slate-300 bg-white p-10 text-center"><Bell className="mx-auto h-9 w-9 text-slate-400" /><p className="mt-4 text-sm font-bold text-slate-500">لا توجد إشعارات بعد.</p></div>}</section>}</div></main></div>;
}
