import AppHeader from "@/components/AppHeader";
import { trpc } from "@/lib/trpc";
import { Clock3, MapPin, Navigation, Route, ShieldCheck } from "lucide-react";
import { useRoute } from "wouter";

const labels: Record<string, string> = { new: "جارٍ البحث عن سائق", assigned: "تم تعيين السائق", driver_arrived: "وصل السائق إلى الاستلام", picked_up: "تم استلام الطلب", in_delivery: "في الطريق للتسليم", delivered: "تم التسليم", cancelled: "تم إلغاء الطلب" };
export default function SharedTracking() {
  const [, params] = useRoute("/shared/:token"); const tracking = trpc.shared.tracking.useQuery({ token: params?.token || "" }, { enabled: Boolean(params?.token), refetchInterval: 10000 });
  const order = tracking.data; const mapUrl = order?.driverLocation ? `https://www.google.com/maps/dir/?api=1&destination=${order.driverLocation.latitude},${order.driverLocation.longitude}` : null;
  return <div dir="rtl" className="min-h-screen bg-[#f8fbfc]"><AppHeader /><main className="container py-10 sm:py-16"><div className="mx-auto max-w-2xl">{tracking.isLoading ? <div className="h-80 animate-pulse rounded-[2rem] bg-slate-200" /> : !order ? <section className="rounded-[2rem] border border-rose-100 bg-white p-10 text-center shadow-sm"><ShieldCheck className="mx-auto h-10 w-10 text-rose-500" /><h1 className="mt-4 text-2xl font-black text-[#082538]">رابط التتبع غير متاح</h1><p className="mt-2 text-sm font-medium text-slate-600">قد يكون الرابط أُوقف أو لم يعد صالحًا.</p></section> : <><header className="rounded-[2rem] bg-[#082538] p-7 text-white shadow-xl"><p className="text-xs font-extrabold text-teal-300">تتبع مشترك</p><h1 className="mt-2 text-3xl font-black">الطلب {order.reference}</h1><div className="mt-5 flex items-center gap-3 rounded-2xl bg-white/10 p-4"><Route className="h-6 w-6 text-teal-300" /><div><p className="font-black">{labels[order.status] || order.status}</p><p className="mt-1 text-xs font-bold text-white/70">وقت تقديري: {order.estimatedMinutes} دقيقة</p></div></div></header><section className="mt-6 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="space-y-5"><div className="flex gap-3"><span className="rounded-xl bg-teal-50 p-2 text-teal-700"><MapPin className="h-5 w-5" /></span><div><p className="text-xs font-bold text-slate-400">من</p><p className="mt-1 font-black text-[#082538]">{order.pickupAddress}</p></div></div><div className="flex gap-3"><span className="rounded-xl bg-sky-50 p-2 text-sky-700"><MapPin className="h-5 w-5" /></span><div><p className="text-xs font-bold text-slate-400">إلى</p><p className="mt-1 font-black text-[#082538]">{order.destinationAddress}</p></div></div>{mapUrl && <a href={mapUrl} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-4 py-3 text-sm font-extrabold text-white"><Navigation className="h-4 w-4" />فتح موقع السائق على الخريطة</a>}</div></section><p className="mt-5 flex items-center justify-center gap-2 text-center text-xs font-bold text-slate-500"><ShieldCheck className="h-4 w-4 text-teal-700" />هذا الرابط لا يعرض رقم الهاتف أو المحادثة أو بيانات الحساب.</p></>}</div></main></div>;
}
