import { useAuth } from "@/_core/hooks/useAuth";
import AppHeader from "@/components/AppHeader";
import { VoiceRecorder } from "@/components/VoiceRecorder";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { MapView } from "@/components/Map";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { audioExtension, blobToBase64 } from "@/lib/media";
import { estimateDriverArrivalMinutes } from "@shared/eta";
import { CANCELLATION_REASONS } from "@shared/cancellation";
import { ArrowRight, Bike, CheckCircle2, Clock3, Info, MapPin, MessageCircle, Package, Phone, Route, Send, ShieldCheck, UserRound, XCircle } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Link, useRoute } from "wouter";

const statusMeta: Record<string, { label: string; tone: string }> = {
  new: { label: "بانتظار موافقة سائق", tone: "bg-blue-50 text-blue-700" },
  assigned: { label: "تم قبول السائق", tone: "bg-teal-50 text-teal-800" },
  driver_arrived: { label: "السائق وصل", tone: "bg-teal-50 text-teal-800" },
  picked_up: { label: "تم الاستلام", tone: "bg-amber-50 text-amber-800" },
  in_delivery: { label: "جاري التوصيل", tone: "bg-violet-50 text-violet-800" },
  delivered: { label: "تم التسليم", tone: "bg-emerald-50 text-emerald-800" },
  cancelled: { label: "ملغى", tone: "bg-rose-50 text-rose-700" },
};

const dateFormatter = new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium", timeStyle: "short" });

export default function TrackOrder() {
  const [, params] = useRoute("/track/:reference");
  const reference = params?.reference || "";
  const { isAuthenticated, loading, user } = useAuth();
  const utils = trpc.useUtils();
  const [message, setMessage] = useState("");
  const [cancelReason, setCancelReason] = useState("");
  const [cancelOpen, setCancelOpen] = useState(false);
  const [cancelledLocally, setCancelledLocally] = useState(false);
  const [liveLocationMessageId, setLiveLocationMessageId] = useState<number | null>(null);

  const tracking = trpc.orders.track.useQuery({ reference }, { enabled: Boolean(reference && isAuthenticated), refetchInterval: 5000 });
  const driver = tracking.data?.driver;
  const driverChat = trpc.orders.driverChat.useQuery({ reference }, { enabled: Boolean(reference && isAuthenticated && driver), refetchInterval: 5000 });
  const unreadCounts = trpc.support.unreadCounts.useQuery(undefined, { enabled: isAuthenticated, refetchInterval: 5000 });
  const markRead = trpc.orders.markDriverChatRead.useMutation({ onSuccess: () => utils.support.unreadCounts.invalidate() });
  const sendMessage = trpc.orders.sendDriverMessage.useMutation({ onSuccess: () => { setMessage(""); utils.orders.driverChat.invalidate({ reference }); }, onError: (error) => toast.error(error.message) });
  const sendAudio = trpc.orders.sendDriverAudio.useMutation({ onSuccess: () => utils.orders.driverChat.invalidate({ reference }), onError: (error) => toast.error(error.message) });
  const shareLocation = trpc.orders.shareLocation.useMutation({ onSuccess: (id) => { setLiveLocationMessageId(Number(id)); utils.orders.driverChat.invalidate({ reference }); toast.success("تمت مشاركة موقعك المباشر."); }, onError: (error) => toast.error(error.message) });
  const updateLocation = trpc.orders.updateLiveLocation.useMutation({ onSuccess: () => utils.orders.driverChat.invalidate({ reference }), onError: (error) => toast.error(error.message) });
  const cancelOrder = trpc.orders.cancel.useMutation({ onSuccess: () => { setCancelledLocally(true); setLiveLocationMessageId(null); setCancelOpen(false); utils.orders.track.invalidate({ reference }); utils.orders.mine.invalidate(); toast.success("تم إلغاء الطلب وإبلاغ الطرف الآخر."); }, onError: (error) => toast.error(error.message) });

  useEffect(() => {
    if (driverChat.data?.messages?.length) markRead.mutate({ reference });
  }, [driverChat.data?.messages?.length, reference]);

  useEffect(() => {
    if (!liveLocationMessageId || !navigator.geolocation) return;
    const watchId = navigator.geolocation.watchPosition((position) => updateLocation.mutate({ messageId: liveLocationMessageId, latitude: position.coords.latitude, longitude: position.coords.longitude, isLive: true }));
    return () => navigator.geolocation.clearWatch(watchId);
  }, [liveLocationMessageId]);

  const order = tracking.data?.order;
  const canCancel = Boolean(order && !cancelledLocally && ["new", "assigned", "driver_arrived"].includes(order.status));
  const eta = useMemo(() => order && driver && ["assigned", "driver_arrived"].includes(order.status) ? estimateDriverArrivalMinutes(order, driver) : null, [order, driver]);
  const center = order && typeof order.pickupLatitude === "number" && typeof order.pickupLongitude === "number" ? { lat: order.pickupLatitude, lng: order.pickupLongitude } : { lat: 27.2579, lng: 33.8116 };

  const submit = (event: FormEvent) => { event.preventDefault(); if (message.trim()) sendMessage.mutate({ reference, body: message }); };
  const recordAudio = async (blob: Blob, durationSeconds: number) => {
    const mimeType = (blob.type.split(";")[0] || "audio/webm") as "audio/webm" | "audio/ogg" | "audio/mp4" | "audio/mpeg";
    sendAudio.mutate({ reference, fileName: `voice-${Date.now()}.${audioExtension(mimeType)}`, mimeType, dataBase64: await blobToBase64(blob), durationSeconds });
  };
  const startSharing = () => {
    if (!navigator.geolocation || !order) { toast.error("لا تتوفر خدمة تحديد الموقع في هذا المتصفح."); return; }
    navigator.geolocation.getCurrentPosition((position) => shareLocation.mutate({ orderId: order.id, latitude: position.coords.latitude, longitude: position.coords.longitude }), () => toast.error("تعذر الوصول إلى موقعك. تحقق من الإذن."));
  };

  if (!loading && !isAuthenticated) return <div dir="rtl" className="min-h-screen bg-[#f8fbfc]"><AppHeader /><main className="container py-16"><section className="mx-auto max-w-xl rounded-[2rem] border border-slate-200 bg-white p-10 text-center shadow-sm"><Route className="mx-auto h-10 w-10 text-teal-700" /><h1 className="mt-5 text-2xl font-black text-[#082538]">سجّل الدخول لمتابعة الطلب</h1><p className="mt-3 text-sm font-medium leading-7 text-slate-600">تابع حالة الرحلة وتواصل مع المندوب من الحساب الذي أنشأ الطلب.</p><button onClick={() => startLogin()} className="mt-6 rounded-xl bg-teal-600 px-5 py-3 text-sm font-extrabold text-white">تسجيل الدخول</button></section></main></div>;
  if (tracking.isLoading || loading) return <div dir="rtl" className="min-h-screen bg-[#f8fbfc]"><AppHeader /><main className="container py-12"><div className="h-12 w-52 animate-pulse rounded-xl bg-slate-200" /><div className="mt-7 h-[420px] animate-pulse rounded-[2rem] bg-slate-200" /></main></div>;
  if (!order) return <div dir="rtl" className="min-h-screen bg-[#f8fbfc]"><AppHeader /><main className="container py-16"><section className="rounded-[2rem] border border-dashed border-slate-300 bg-white p-10 text-center"><Route className="mx-auto h-10 w-10 text-slate-400" /><h1 className="mt-5 text-xl font-black text-[#082538]">لم نعثر على هذا الطلب</h1><Link href="/my-orders" className="mt-6 inline-flex rounded-xl bg-[#082538] px-5 py-3 text-sm font-extrabold text-white no-underline">العودة لطلباتي</Link></section></main></div>;

  const status = statusMeta[order.status] || { label: order.status, tone: "bg-slate-100 text-slate-700" };
  const ServiceIcon = order.serviceType === "person" ? UserRound : Package;

  return <div dir="rtl" className="min-h-screen bg-[#f8fbfc] text-slate-950"><AppHeader /><main className="container py-8 sm:py-12"><Link href="/my-orders" className="inline-flex items-center gap-2 text-sm font-extrabold text-slate-600 no-underline hover:text-teal-700"><ArrowRight className="h-4 w-4" /> العودة لطلباتي</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-extrabold tracking-[.16em] text-teal-700">تتبع تشغيلي</p><h1 className="mt-2 text-3xl font-black text-[#082538]">طلب {order.reference}</h1><p className="mt-2 text-sm font-medium text-slate-600">أُنشئ في {dateFormatter.format(new Date(order.createdAt))}</p></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-4 py-2 text-sm font-extrabold ${status.tone}`}>{status.label}</span>{canCancel && <button type="button" onClick={() => setCancelOpen(true)} className="rounded-full border border-rose-200 bg-rose-50 px-4 py-2 text-sm font-extrabold text-rose-700 transition hover:bg-rose-100 active:scale-[.97]">إلغاء الطلب</button>}</div></div>
    {(cancelledLocally || order.status === "cancelled") && <section aria-live="polite" className="mt-6 flex items-center gap-4 rounded-[2rem] border border-rose-200 bg-rose-50 p-5 shadow-sm"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-rose-600 text-white"><XCircle className="h-6 w-6" /></span><div><p className="text-sm font-black text-rose-900">تم إلغاء الطلب</p><p className="mt-1 text-xs font-bold leading-6 text-rose-800">تم تسجيل الإلغاء وإبلاغ الطرف الآخر، وأُوقفت أي مشاركة موقع مباشرة مرتبطة بالطلب.</p></div></section>}
    {order.status === "new" && !driver && <section className="mt-6 flex items-center gap-4 rounded-[2rem] border border-blue-100 bg-gradient-to-l from-blue-50 via-white to-teal-50 p-5 shadow-sm"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-white text-teal-700 shadow-sm"><Bike className="h-7 w-7 animate-pulse motion-reduce:animate-none" /></span><div><p className="text-sm font-black text-[#082538]">نبحث لك عن أقرب سائق</p><p className="mt-1 text-xs font-bold leading-6 text-slate-500">سيصل تأكيد واضح فور قبول أحد السائقين للدعوة.</p></div></section>}
    {order.status === "assigned" && driver && <section aria-live="polite" className="mt-6 rounded-[2rem] border border-violet-100 bg-gradient-to-l from-violet-50 via-white to-blue-50 p-5 shadow-sm"><div className="flex items-center gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-violet-600 text-white"><Bike className="h-7 w-7" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-black text-[#082538]">تم تأكيد السائق وهو في الطريق إليك</p><span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-black text-violet-700">الوصول خلال {eta} د تقريبًا</span></div><p className="mt-2 text-xs font-bold text-slate-500">يتحدث الوقت تلقائيًا عند وصول موقع السائق.</p></div></div></section>}
    <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-[300px] bg-slate-100"><MapView className="h-full" initialCenter={center} initialZoom={13} /></div><div className="grid gap-4 p-5 sm:grid-cols-2"><div className="flex gap-3"><span className="rounded-xl bg-teal-50 p-2.5 text-teal-700"><MapPin className="h-5 w-5" /></span><div><p className="text-xs font-bold text-slate-400">نقطة الاستلام</p><p className="mt-1 text-sm font-black text-slate-800">{order.pickupAddress}</p></div></div><div className="flex gap-3"><span className="rounded-xl bg-orange-50 p-2.5 text-[#df6547]"><MapPin className="h-5 w-5" /></span><div><p className="text-xs font-bold text-slate-400">نقطة التسليم</p><p className="mt-1 text-sm font-black text-slate-800">{order.destinationAddress}</p></div></div></div></section><aside className="rounded-[2rem] bg-[#082538] p-6 text-white shadow-[0_20px_40px_rgba(8,37,56,.18)]"><span className="inline-flex rounded-xl bg-white/10 p-2"><ServiceIcon className="h-5 w-5" /></span><p className="mt-5 text-xs font-bold text-teal-300">معلومات الرحلة</p><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-3 text-center"><p className="text-[11px] text-slate-300">المسافة</p><p className="mt-1 font-black">{order.distanceMeters ? `${(order.distanceMeters / 1000).toFixed(1)} كم` : "—"}</p></div><div className="rounded-xl bg-white/10 p-3 text-center"><p className="text-[11px] text-slate-300">الوقت</p><p className="mt-1 font-black">{order.estimatedMinutes || "—"} د</p></div></div>{driver ? <div className="mt-5 rounded-xl bg-white/10 p-4"><p className="text-xs font-bold text-teal-300">المندوب المعيّن</p><p className="mt-2 flex items-center gap-2 text-sm font-black"><Bike className="h-4 w-4" /> {driver.displayName}</p><a href={`tel:${driver.phone}`} className="mt-3 flex items-center justify-center gap-2 rounded-lg bg-white/10 px-3 py-2 text-xs font-bold text-white no-underline"><Phone className="h-3.5 w-3.5" /> الاتصال بالمندوب</a></div> : <p className="mt-5 rounded-xl bg-white/10 p-4 text-xs font-bold text-slate-300">سيظهر المندوب بعد قبول الدعوة.</p>}</aside></div>
    {driver && <section className="mt-7 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-[#effcf9] p-2.5 text-teal-700"><MessageCircle className="h-5 w-5" /></span><div><div className="flex items-center gap-2"><h2 className="font-black text-[#082538]">التواصل مع المندوب</h2>{Boolean(unreadCounts.data?.driver) && <span className="rounded-full bg-rose-100 px-2 py-1 text-[11px] font-black text-rose-700">{unreadCounts.data?.driver} جديدة</span>}</div><p className="mt-1 text-xs font-medium text-slate-500">تتحدث المحادثة تلقائيًا كل بضع ثوانٍ.</p></div></div><div className="mt-5 max-h-64 space-y-3 overflow-y-auto rounded-2xl bg-slate-50 p-4">{driverChat.data?.messages?.length ? driverChat.data.messages.map((chat) => <div key={chat.id} className={`rounded-2xl px-4 py-3 text-sm font-medium ${chat.messageType === "system" ? "border border-amber-200 bg-amber-50 text-amber-900" : chat.senderUserId === user?.id ? "mr-auto max-w-[82%] bg-[#082538] text-white" : "max-w-[82%] bg-white text-slate-700 shadow-sm"}`}>{chat.messageType === "system" ? <div className="flex flex-wrap items-center justify-between gap-3"><span className="flex items-center gap-2 font-black"><Info className="h-4 w-4" />{chat.body}</span><time className="text-[11px] font-extrabold">{dateFormatter.format(new Date(chat.createdAt))}</time></div> : chat.messageType === "audio" && chat.attachmentUrl ? <audio controls preload="metadata" className="max-w-full" src={chat.attachmentUrl} /> : chat.messageType === "location" ? <span className="flex items-center gap-2 text-xs font-black text-teal-700"><MapPin className="h-4 w-4" />{chat.locationIsLive ? "موقع مباشر" : "موقع مشترك"}</span> : <p>{chat.body}</p>}</div>) : <p className="py-6 text-center text-sm font-bold text-slate-500">لا توجد رسائل بعد.</p>}</div><form onSubmit={submit} className="mt-4 flex gap-2">{liveLocationMessageId ? <button type="button" onClick={() => updateLocation.mutate({ messageId: liveLocationMessageId, isLive: false }, { onSuccess: () => setLiveLocationMessageId(null) })} className="rounded-xl border border-rose-200 bg-rose-50 px-3 text-rose-700">إيقاف</button> : <button type="button" onClick={startSharing} className="rounded-xl border border-teal-200 bg-teal-50 px-3 text-teal-700" aria-label="مشاركة الموقع"><MapPin className="h-5 w-5" /></button>}<VoiceRecorder disabled={sendAudio.isPending} onRecorded={recordAudio} /><input required value={message} onChange={(event) => setMessage(event.target.value)} placeholder="اكتب رسالة للمندوب..." className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm" /><button disabled={sendMessage.isPending} className="rounded-xl bg-teal-600 px-4 text-white"><Send className="h-5 w-5" /></button></form></section>}
    <section className="mt-7 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-[#effcf9] p-2.5 text-teal-700"><Clock3 className="h-5 w-5" /></span><div><h2 className="font-black text-[#082538]">المخطط الزمني للطلب</h2><p className="mt-1 text-xs font-medium text-slate-500">كل إجراء تشغيلي موثق بوقته.</p></div></div><ol className="mt-6 space-y-4 border-r-2 border-teal-100 pr-6">{tracking.data?.events?.map((event) => <li key={event.id} className="relative"><span className="absolute -right-[1.8rem] top-1 h-3 w-3 rounded-full bg-teal-500 ring-4 ring-white" /><p className="text-sm font-black text-[#082538]">{event.note || statusMeta[event.status]?.label || "تحديث الطلب"}</p><p className="mt-1 text-xs font-medium text-slate-500">{dateFormatter.format(new Date(event.createdAt))}</p></li>)}</ol></section>
    <AlertDialog open={cancelOpen} onOpenChange={setCancelOpen}><AlertDialogContent dir="rtl" className="max-w-md rounded-[2rem]"><AlertDialogHeader><AlertDialogTitle className="text-right text-xl font-black text-[#082538]">إلغاء الطلب؟</AlertDialogTitle><AlertDialogDescription className="text-right leading-7">يمكنك الإلغاء قبل استلام الطلب أو بدء التوصيل. سيصل إشعار إلى السائق وتُغلق الدعوات ومشاركة الموقع المرتبطة بالطلب.</AlertDialogDescription></AlertDialogHeader><label className="grid gap-2 text-right text-sm font-bold text-slate-700">سبب الإلغاء <span className="text-rose-600">*</span><select required value={cancelReason} onChange={(event) => setCancelReason(event.target.value)} className="rounded-xl border border-slate-200 bg-white p-3 text-sm font-bold text-slate-800 outline-none focus:border-rose-400"><option value="" disabled>اختر سبب الإلغاء</option>{CANCELLATION_REASONS.map((reason) => <option key={reason} value={reason}>{reason}</option>)}</select><span className="text-xs font-medium text-slate-500">اختيار السبب مطلوب لتأكيد الإلغاء.</span></label><AlertDialogFooter className="gap-2 sm:justify-start"><AlertDialogAction onClick={() => cancelOrder.mutate({ reference, reason: cancelReason as typeof CANCELLATION_REASONS[number] })} disabled={!cancelReason || cancelOrder.isPending} className="bg-rose-600 hover:bg-rose-700 disabled:opacity-50">{cancelOrder.isPending ? "جارٍ الإلغاء..." : "تأكيد الإلغاء"}</AlertDialogAction><AlertDialogCancel disabled={cancelOrder.isPending}>العودة للطلب</AlertDialogCancel></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main></div>;
}
