import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { z } from "zod";
import { acceptOrderForDriver, cancelOrderForCustomer, attachVodafonePaymentReceipt, createCoupon, createDeliveryOrder, createDriverForUser, createLiveLocationMessage, getAdminCoupons, getAdminDailyReport, getAdminDrivers, getAdminFeedback, getAdminOperationalAuditLog, getAdminOrders, getAdminPaymentOrders, getAdminSummary, getAdminSupportInbox, getAdminUsers, getAdminWithdrawalRequests, getDeliveryOrderWithEventsForUser, getDeliveryOrdersForUser, getDriverByUserId, getDriverChatForCustomer, getDriverChatForDriver, getDriverFinancialSummary, getNewOrdersForDriver, getNotificationsForUser, getOrderFeedbackForCustomer, getOrdersForDriver, getServicePricingRuleMap, getUnreadMessageCounts, requestDriverWithdrawal, resolveCouponForOrder, reviewDeliveryComplaint, reviewDriverWithdrawal, sendCustomerDriverAudio, sendDriverCustomerAudio, sendSupportAudio, setDriverCommissionPercent, submitDeliveryComplaint, submitOrderReview, updateCouponStatus, updateLiveLocation, updateServicePricingRule, getProfileWithAddresses, getSupportConversation, markCustomerDriverChatRead, rejectOrderInvitation, markDriverChatRead, markSupportMessagesRead, saveAddressForUser, sendAdminSupportReply, sendCustomerDriverMessage, sendDriverCustomerMessage, sendSupportMessage, setDriverAdminStatus, updateContactForUser, updateDriverAvailability, updateDriverLocation, updateDriverOrderStatus, verifyVodafonePayment } from "./db";
import { buildOperationalQuote, deliveryOrderInput, makeOrderReference } from "./delivery";
import { getVodafoneCashInstructions } from "./payment";
import { CANCELLATION_REASONS } from "../shared/cancellation";
import { storagePut } from "./storage";
import { MAX_AUDIO_BYTES, validateAudioUpload } from "@shared/chat-media";

const availabilityInput = z.enum(["offline", "online", "busy", "suspended"]);
const driverStatusInput = z.enum(["driver_arrived", "picked_up", "in_delivery", "delivered"]);

export const appRouter = router({
  system: systemRouter,
  payment: router({ config: publicProcedure.query(() => getVodafoneCashInstructions()) }),
  pricing: router({ rules: publicProcedure.query(() => getServicePricingRuleMap()) }),
  auth: router({ me: publicProcedure.query((opts) => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  orders: router({
    create: protectedProcedure.input(deliveryOrderInput).mutation(async ({ ctx, input }) => { const quote = buildOperationalQuote(input, await getServicePricingRuleMap()); const coupon = await resolveCouponForOrder(input.couponCode, quote.estimatedFee); return createDeliveryOrder({ reference: makeOrderReference(), userId: ctx.user.id, serviceType: input.serviceType, customerName: input.customerName, customerPhone: input.customerPhone, pickupAddress: input.pickupAddress, pickupLatitude: input.pickupLatitude ?? null, pickupLongitude: input.pickupLongitude ?? null, destinationAddress: input.destinationAddress, destinationLatitude: input.destinationLatitude ?? null, destinationLongitude: input.destinationLongitude ?? null, requestedFor: new Date(input.requestedFor), recipientName: input.recipientName || null, recipientPhone: input.recipientPhone || null, arrivalNotes: input.arrivalNotes || null, packageDescription: input.packageDescription || null, packageSize: input.packageSize, itemCount: input.itemCount, contactless: input.contactless ? 1 : 0, healthNotes: input.healthNotes || null, distanceMeters: quote.distanceMeters, estimatedMinutes: quote.estimatedMinutes, fareBeforeDiscount: quote.estimatedFee, estimatedFee: coupon.finalFee, couponCode: coupon.coupon?.code || null, couponDiscount: coupon.couponDiscount, paymentMethod: input.paymentMethod, paymentReference: input.paymentReference || null, paymentStatus: input.paymentMethod === "vodafone_cash" ? "verifying" : "pending" }, coupon.coupon?.id); }),

    mine: protectedProcedure.query(({ ctx }) => getDeliveryOrdersForUser(ctx.user.id)),
    track: protectedProcedure.input(z.object({ reference: z.string().min(5) })).query(({ ctx, input }) => getDeliveryOrderWithEventsForUser(input.reference, ctx.user.id)),
    cancel: protectedProcedure.input(z.object({ reference: z.string().min(5), reason: z.enum(CANCELLATION_REASONS) })).mutation(({ ctx, input }) => cancelOrderForCustomer(input.reference, ctx.user.id, input.reason)),
    driverChat: protectedProcedure.input(z.object({ reference: z.string().min(5) })).query(({ ctx, input }) => getDriverChatForCustomer(input.reference, ctx.user.id)),
    sendDriverMessage: protectedProcedure.input(z.object({ reference: z.string().min(5), body: z.string().trim().min(1).max(1200) })).mutation(({ ctx, input }) => sendCustomerDriverMessage(input.reference, ctx.user.id, input.body)),
    sendDriverAudio: protectedProcedure.input(z.object({ reference: z.string().min(5), fileName: z.string().trim().regex(/^[A-Za-z0-9._-]{1,120}$/), mimeType: z.enum(["audio/webm", "audio/ogg", "audio/mp4", "audio/mpeg"]), dataBase64: z.string().min(20).max(7000000), durationSeconds: z.number().int().min(1).max(600) })).mutation(async ({ ctx, input }) => { const bytes = Buffer.from(input.dataBase64, "base64"); if (!validateAudioUpload(bytes.byteLength, input.mimeType, input.durationSeconds)) throw new Error(`الرسالة الصوتية يجب أن تكون من نوع مدعوم وألا تتجاوز ${MAX_AUDIO_BYTES / 1_000_000} ميجابايت و10 دقائق.`); const uploaded = await storagePut(`chat-audio/${ctx.user.id}/${input.fileName}`, bytes, input.mimeType); return sendCustomerDriverAudio(input.reference, ctx.user.id, uploaded.url, input.fileName, input.durationSeconds); }),
    shareLocation: protectedProcedure.input(z.object({ orderId: z.number().int().positive(), latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180) })).mutation(({ ctx, input }) => createLiveLocationMessage(input.orderId, ctx.user.id, input.latitude, input.longitude)),
    updateLiveLocation: protectedProcedure.input(z.object({ messageId: z.number().int().positive(), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional(), isLive: z.boolean().default(true) })).mutation(({ ctx, input }) => updateLiveLocation(input.messageId, ctx.user.id, input.latitude, input.longitude, input.isLive)),
    markDriverChatRead: protectedProcedure.input(z.object({ reference: z.string().min(5) })).mutation(({ ctx, input }) => markCustomerDriverChatRead(input.reference, ctx.user.id)),
    uploadPaymentReceipt: protectedProcedure.input(z.object({ orderId: z.number().int().positive(), fileName: z.string().trim().regex(/^[A-Za-z0-9._-]{1,120}$/), mimeType: z.enum(["image/jpeg", "image/png", "application/pdf"]), dataBase64: z.string().min(20).max(6000000) })).mutation(async ({ ctx, input }) => { const bytes = Buffer.from(input.dataBase64, "base64"); if (bytes.byteLength > 4_000_000) throw new Error("حجم الإيصال يجب ألا يتجاوز 4 ميجابايت."); const uploaded = await storagePut(`payment-receipts/${ctx.user.id}/${input.orderId}-${input.fileName}`, bytes, input.mimeType); return attachVodafonePaymentReceipt(input.orderId, ctx.user.id, uploaded.url); }),
    feedback: protectedProcedure.input(z.object({ reference: z.string().min(5) })).query(({ ctx, input }) => getOrderFeedbackForCustomer(input.reference, ctx.user.id)),
    submitReview: protectedProcedure.input(z.object({ reference: z.string().min(5), rating: z.number().int().min(1).max(5), comment: z.string().trim().max(800).optional() })).mutation(({ ctx, input }) => submitOrderReview({ ...input, customerUserId: ctx.user.id })),
    submitComplaint: protectedProcedure.input(z.object({ reference: z.string().min(5), category: z.enum(["driver_behavior", "delay", "item_issue", "payment", "safety", "other"]), description: z.string().trim().min(10).max(1600) })).mutation(({ ctx, input }) => submitDeliveryComplaint({ ...input, customerUserId: ctx.user.id })),
  }),
  coupons: router({ preview: protectedProcedure.input(z.object({ code: z.string().trim().min(3).max(40), fareBeforeDiscount: z.number().int().positive() })).query(({ input }) => resolveCouponForOrder(input.code, input.fareBeforeDiscount)) }),
  driver: router({
    me: protectedProcedure.query(({ ctx }) => getDriverByUserId(ctx.user.id)),
    setAvailability: protectedProcedure.input(z.object({ availability: availabilityInput })).mutation(async ({ ctx, input }) => { const driver = await getDriverByUserId(ctx.user.id); if (!driver) throw new Error("لا يوجد ملف مندوب مرتبط بهذا الحساب."); return updateDriverAvailability(driver.id, input.availability); }),
    updateLocation: protectedProcedure.input(z.object({ latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180) })).mutation(async ({ ctx, input }) => { const driver = await getDriverByUserId(ctx.user.id); if (!driver) throw new Error("لا يوجد ملف مندوب مرتبط بهذا الحساب."); return updateDriverLocation(driver.id, input.latitude, input.longitude); }),
    openOrders: protectedProcedure.query(({ ctx }) => getDriverByUserId(ctx.user.id).then((driver) => driver ? getNewOrdersForDriver(driver.id) : [])),
    myOrders: protectedProcedure.query(async ({ ctx }) => { const driver = await getDriverByUserId(ctx.user.id); return driver ? getOrdersForDriver(driver.id) : []; }),
    accept: protectedProcedure.input(z.object({ orderId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const driver = await getDriverByUserId(ctx.user.id); if (!driver) throw new Error("لا يوجد ملف مندوب مرتبط بهذا الحساب."); return acceptOrderForDriver(input.orderId, driver.id, ctx.user.id); }),
    reject: protectedProcedure.input(z.object({ orderId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const driver = await getDriverByUserId(ctx.user.id); if (!driver) throw new Error("لا يوجد ملف مندوب مرتبط بهذا الحساب."); return rejectOrderInvitation(input.orderId, driver.id); }),
    updateStatus: protectedProcedure.input(z.object({ orderId: z.number().int().positive(), status: driverStatusInput })).mutation(async ({ ctx, input }) => { const driver = await getDriverByUserId(ctx.user.id); if (!driver) throw new Error("لا يوجد ملف مندوب مرتبط بهذا الحساب."); return updateDriverOrderStatus(input.orderId, driver.id, ctx.user.id, input.status); }),
    chat: protectedProcedure.input(z.object({ orderId: z.number().int().positive() })).query(({ ctx, input }) => getDriverChatForDriver(input.orderId, ctx.user.id)),
    sendChat: protectedProcedure.input(z.object({ orderId: z.number().int().positive(), body: z.string().trim().min(1).max(1200) })).mutation(({ ctx, input }) => sendDriverCustomerMessage(input.orderId, ctx.user.id, input.body)),
    sendAudio: protectedProcedure.input(z.object({ orderId: z.number().int().positive(), fileName: z.string().trim().regex(/^[A-Za-z0-9._-]{1,120}$/), mimeType: z.enum(["audio/webm", "audio/ogg", "audio/mp4", "audio/mpeg"]), dataBase64: z.string().min(20).max(7000000), durationSeconds: z.number().int().min(1).max(600) })).mutation(async ({ ctx, input }) => { const bytes = Buffer.from(input.dataBase64, "base64"); if (!validateAudioUpload(bytes.byteLength, input.mimeType, input.durationSeconds)) throw new Error(`الرسالة الصوتية يجب أن تكون من نوع مدعوم وألا تتجاوز ${MAX_AUDIO_BYTES / 1_000_000} ميجابايت و10 دقائق.`); const uploaded = await storagePut(`chat-audio/${ctx.user.id}/${input.fileName}`, bytes, input.mimeType); return sendDriverCustomerAudio(input.orderId, ctx.user.id, uploaded.url, input.fileName, input.durationSeconds); }),
    shareLocation: protectedProcedure.input(z.object({ orderId: z.number().int().positive(), latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180) })).mutation(({ ctx, input }) => createLiveLocationMessage(input.orderId, ctx.user.id, input.latitude, input.longitude)),
    updateLiveLocation: protectedProcedure.input(z.object({ messageId: z.number().int().positive(), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional(), isLive: z.boolean().default(true) })).mutation(({ ctx, input }) => updateLiveLocation(input.messageId, ctx.user.id, input.latitude, input.longitude, input.isLive)),
    markChatRead: protectedProcedure.input(z.object({ orderId: z.number().int().positive() })).mutation(({ ctx, input }) => markDriverChatRead(input.orderId, ctx.user.id)),
    earnings: protectedProcedure.query(({ ctx }) => getDriverFinancialSummary(ctx.user.id)),
    requestWithdrawal: protectedProcedure.input(z.object({ amount: z.number().int().positive(), note: z.string().trim().max(500).optional() })).mutation(({ ctx, input }) => requestDriverWithdrawal({ userId: ctx.user.id, ...input })),
  }),
  admin: router({
    summary: adminProcedure.query(() => getAdminSummary()), dailyReport: adminProcedure.query(() => getAdminDailyReport()), users: adminProcedure.query(() => getAdminUsers()), drivers: adminProcedure.query(() => getAdminDrivers()), orders: adminProcedure.query(() => getAdminOrders()), payments: adminProcedure.query(() => getAdminPaymentOrders()), auditLog: adminProcedure.query(() => getAdminOperationalAuditLog()), supportInbox: adminProcedure.query(({ ctx }) => getAdminSupportInbox(ctx.user.id)), pricingRules: adminProcedure.query(() => getServicePricingRuleMap()), withdrawalRequests: adminProcedure.query(() => getAdminWithdrawalRequests()), feedback: adminProcedure.query(() => getAdminFeedback()), coupons: adminProcedure.query(() => getAdminCoupons()),
    createDriver: adminProcedure.input(z.object({ userId: z.number().int().positive(), displayName: z.string().min(2).max(120), phone: z.string().min(8).max(32), vehicleType: z.string().min(2).max(64), vehiclePlate: z.string().max(32).optional(), commissionPercent: z.number().int().min(0).max(80).default(10) })).mutation(({ input }) => createDriverForUser(input)),
    updateDriverStatus: adminProcedure.input(z.object({ driverId: z.number().int().positive(), availability: z.enum(["offline", "online", "suspended"]) })).mutation(({ input }) => setDriverAdminStatus(input.driverId, input.availability)),
    updateDriverCommission: adminProcedure.input(z.object({ driverId: z.number().int().positive(), commissionPercent: z.number().int().min(0).max(80) })).mutation(({ input }) => setDriverCommissionPercent(input.driverId, input.commissionPercent)),
    updatePricingRule: adminProcedure.input(z.object({ serviceType: z.enum(["person", "parcel", "documents", "items", "other"]), baseFare: z.number().int().min(0).max(500), perKmFare: z.number().int().min(5).max(200), minimumFare: z.number().int().min(0).max(500) })).mutation(({ ctx, input }) => updateServicePricingRule({ ...input, updatedByUserId: ctx.user.id })),
    reviewWithdrawal: adminProcedure.input(z.object({ withdrawalId: z.number().int().positive(), status: z.enum(["approved", "rejected", "paid"]), adminNote: z.string().trim().max(500).optional() })).mutation(({ ctx, input }) => reviewDriverWithdrawal({ ...input, adminUserId: ctx.user.id })),
    reviewComplaint: adminProcedure.input(z.object({ complaintId: z.number().int().positive(), status: z.enum(["in_review", "resolved", "closed"]), adminNote: z.string().trim().max(1200).optional() })).mutation(({ ctx, input }) => reviewDeliveryComplaint({ ...input, adminUserId: ctx.user.id })),
    createCoupon: adminProcedure.input(z.object({ code: z.string().trim().min(3).max(40), discountType: z.enum(["fixed", "percent"]), discountValue: z.number().int().min(1).max(10000), minimumOrderFee: z.number().int().min(0).max(10000).default(0), maximumDiscount: z.number().int().min(1).max(10000).optional(), maxRedemptions: z.number().int().min(1).max(100000).optional(), startsAt: z.string().datetime().optional(), endsAt: z.string().datetime().optional() })).mutation(({ ctx, input }) => createCoupon({ ...input, maximumDiscount: input.maximumDiscount ?? null, maxRedemptions: input.maxRedemptions ?? null, startsAt: input.startsAt ? new Date(input.startsAt) : null, endsAt: input.endsAt ? new Date(input.endsAt) : null, createdByUserId: ctx.user.id })),
    updateCouponStatus: adminProcedure.input(z.object({ couponId: z.number().int().positive(), status: z.enum(["active", "paused", "expired"]) })).mutation(({ input }) => updateCouponStatus(input.couponId, input.status)),
    replySupport: adminProcedure.input(z.object({ recipientUserId: z.number().int().positive(), body: z.string().trim().min(1).max(1200) })).mutation(({ ctx, input }) => sendAdminSupportReply({ adminUserId: ctx.user.id, ...input })),
    verifyPayment: adminProcedure.input(z.object({ orderId: z.number().int().positive(), status: z.enum(["paid", "failed"]) })).mutation(({ ctx, input }) => verifyVodafonePayment(input.orderId, ctx.user.id, input.status)),
  }),
  profile: router({
    me: protectedProcedure.query(({ ctx }) => getProfileWithAddresses(ctx.user.id)),
    saveAddress: protectedProcedure.input(z.object({ label: z.string().trim().min(2).max(80), address: z.string().trim().min(5).max(500), isFavorite: z.boolean().default(false) })).mutation(({ ctx, input }) => saveAddressForUser({ userId: ctx.user.id, ...input })),
    updateContact: protectedProcedure.input(z.object({ name: z.string().trim().min(2).max(120), phone: z.string().trim().min(8).max(32) })).mutation(({ ctx, input }) => updateContactForUser(ctx.user.id, input.name, input.phone)),
  }),
  support: router({
    conversation: protectedProcedure.query(({ ctx }) => getSupportConversation(ctx.user.id)),
    send: protectedProcedure.input(z.object({ body: z.string().trim().min(1).max(1200), locationLabel: z.string().trim().max(240).optional(), locationLatitude: z.number().min(-90).max(90).optional(), locationLongitude: z.number().min(-180).max(180).optional() })).mutation(({ ctx, input }) => sendSupportMessage({ senderUserId: ctx.user.id, ...input })),
    sendAudio: protectedProcedure.input(z.object({ fileName: z.string().trim().regex(/^[A-Za-z0-9._-]{1,120}$/), mimeType: z.enum(["audio/webm", "audio/ogg", "audio/mp4", "audio/mpeg"]), dataBase64: z.string().min(20).max(7000000), durationSeconds: z.number().int().min(1).max(600) })).mutation(async ({ ctx, input }) => { const bytes = Buffer.from(input.dataBase64, "base64"); if (!validateAudioUpload(bytes.byteLength, input.mimeType, input.durationSeconds)) throw new Error(`الرسالة الصوتية يجب أن تكون من نوع مدعوم وألا تتجاوز ${MAX_AUDIO_BYTES / 1_000_000} ميجابايت و10 دقائق.`); const uploaded = await storagePut(`chat-audio/${ctx.user.id}/${input.fileName}`, bytes, input.mimeType); return sendSupportAudio(ctx.user.id, uploaded.url, input.fileName, input.durationSeconds); }),
    notifications: protectedProcedure.query(({ ctx }) => getNotificationsForUser(ctx.user.id)),
    markRead: protectedProcedure.mutation(({ ctx }) => markSupportMessagesRead(ctx.user.id)),
    unreadCounts: protectedProcedure.query(({ ctx }) => getUnreadMessageCounts(ctx.user.id)),
  }),
});

export type AppRouter = typeof appRouter;
