import { Copy, Link2, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export function ShareTrackingDock() {
  const [location] = useLocation(); const match = location.match(/^\/track\/([^/]+)$/); const [open, setOpen] = useState(false); const [token, setToken] = useState<string | null>(null);
  const share = trpc.orders.shareTracking.useMutation({ onSuccess: (data) => { setToken(data.token); if (data.token) toast.success("تم إنشاء رابط التتبع."); else toast.success("تم إيقاف رابط التتبع."); }, onError: (error) => toast.error(error.message) });
  if (!match) return null;
  const copy = async () => { if (!token) return; await navigator.clipboard?.writeText(`${window.location.origin}/shared/${token}`); toast.success("تم نسخ رابط التتبع."); };
  return <div dir="rtl" className="fixed bottom-5 right-3 z-50 w-[calc(100%-1.5rem)] max-w-sm sm:right-5">{open ? <section className="rounded-2xl border border-sky-100 bg-white p-4 shadow-[0_16px_38px_rgba(8,37,56,.2)]"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black text-[#082538]">مشاركة التتبع</p><p className="mt-1 text-xs font-medium text-slate-500">يعرض الرابط حالة الطلب والمسار فقط، دون بيانات التواصل أو المحادثة.</p></div><button onClick={() => setOpen(false)} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100" aria-label="إغلاق"><X className="h-4 w-4" /></button></div>{token ? <><div className="mt-4 rounded-xl bg-sky-50 p-3 text-xs font-bold text-sky-900"><span className="break-all">{window.location.origin}/shared/{token}</span></div><div className="mt-3 flex gap-2"><button onClick={copy} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#082538] px-3 py-2.5 text-xs font-extrabold text-white"><Copy className="h-4 w-4" />نسخ الرابط</button><button onClick={() => share.mutate({ reference: match[1]!, enabled: false })} disabled={share.isPending} className="rounded-xl border border-rose-200 bg-rose-50 px-3 py-2.5 text-xs font-extrabold text-rose-700">إيقاف</button></div></> : <button onClick={() => share.mutate({ reference: match[1]!, enabled: true })} disabled={share.isPending} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#082538] px-4 py-3 text-sm font-extrabold text-white"><Link2 className="h-4 w-4" />{share.isPending ? "جارٍ الإنشاء…" : "إنشاء رابط تتبع"}</button>}</section> : <button onClick={() => setOpen(true)} className="mr-auto flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-extrabold text-[#082538] shadow-[0_10px_26px_rgba(8,37,56,.16)] ring-1 ring-sky-100 transition hover:bg-sky-50 active:scale-[.97]"><span className="rounded-lg bg-sky-100 p-1.5 text-sky-700"><Link2 className="h-4 w-4" /></span> مشاركة التتبع</button>}</div>;
}
