import { FileImage, Paperclip, Upload, X } from "lucide-react";
import { useRef, useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

function toBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] || ""); reader.onerror = reject; reader.readAsDataURL(file); }); }

export function ShipmentAttachmentDock() {
  const [location] = useLocation(); const match = location.match(/^\/track\/([^/]+)$/); const inputRef = useRef<HTMLInputElement>(null); const [open, setOpen] = useState(false); const utils = trpc.useUtils();
  const tracking = trpc.orders.track.useQuery({ reference: match?.[1] || "" }, { enabled: Boolean(match?.[1]) }); const attachments = trpc.orders.attachments.useQuery({ reference: match?.[1] || "" }, { enabled: Boolean(match?.[1]) });
  const upload = trpc.orders.uploadAttachment.useMutation({ onSuccess: () => { utils.orders.attachments.invalidate({ reference: match?.[1] || "" }); toast.success("تمت إضافة المرفق إلى الطلب."); }, onError: (error) => toast.error(error.message) });
  if (!match || !tracking.data?.order) return null;
  const select = async (file?: File) => { const orderId = tracking.data?.order?.id; if (!file || !orderId) return; if (file.size > 4_000_000) { toast.error("حجم الملف يجب ألا يتجاوز 4 ميجابايت."); return; } if (!["image/jpeg", "image/png", "application/pdf"].includes(file.type)) { toast.error("ارفع صورة JPG أو PNG أو ملف PDF فقط."); return; } const dataBase64 = await toBase64(file); upload.mutate({ orderId, attachmentType: file.type === "application/pdf" ? "other" : "shipment_photo", fileName: file.name.replace(/[^A-Za-z0-9._-]/g, "_"), mimeType: file.type as "image/jpeg" | "image/png" | "application/pdf", dataBase64 }); };
  return <div dir="rtl" className="fixed bottom-5 right-3 z-50 w-[calc(100%-1.5rem)] max-w-sm sm:right-5">{open ? <section className="rounded-2xl border border-violet-100 bg-white p-4 shadow-[0_16px_38px_rgba(8,37,56,.2)]"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black text-[#082538]">صور وملفات الشحنة</p><p className="mt-1 text-xs font-medium text-slate-500">مرتبطة بهذا الطلب فقط وبحد أقصى 4 ميجابايت للملف.</p></div><button onClick={() => setOpen(false)} aria-label="إغلاق" className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"><X className="h-4 w-4" /></button></div><input ref={inputRef} className="hidden" type="file" accept="image/jpeg,image/png,application/pdf" onChange={(event) => { select(event.target.files?.[0]); event.currentTarget.value = ""; }} /><button disabled={upload.isPending} onClick={() => inputRef.current?.click()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#082538] px-4 py-3 text-sm font-extrabold text-white disabled:opacity-60"><Upload className="h-4 w-4" />{upload.isPending ? "جارٍ الرفع…" : "إرفاق صورة أو ملف"}</button><div className="mt-4 max-h-36 space-y-2 overflow-y-auto">{attachments.data?.length ? attachments.data.map((attachment) => <a key={attachment.id} href={attachment.fileUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-xl bg-slate-50 p-2.5 text-xs font-bold text-slate-700"><FileImage className="h-4 w-4 text-violet-700" /><span className="truncate">{attachment.fileName}</span></a>) : <p className="rounded-xl bg-slate-50 p-3 text-center text-xs font-bold text-slate-500">لم تتم إضافة مرفقات بعد.</p>}</div></section> : <button onClick={() => setOpen(true)} className="mr-auto flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-extrabold text-[#082538] shadow-[0_10px_26px_rgba(8,37,56,.16)] ring-1 ring-violet-100 transition hover:bg-violet-50 active:scale-[.97]"><span className="rounded-lg bg-violet-100 p-1.5 text-violet-700"><Paperclip className="h-4 w-4" /></span> مرفقات الشحنة</button>}</div>;
}
